version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: "d0ca4ef4-cd2a-4fc4-8c74-f81c2d98d276"
  endpoints: public
  env:
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
